version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "3333:3333"
    volumes:
      - sqlite-data:/app/prisma
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_REACT_API_URL=http://localhost:3333
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  sqlite-data:

networks:
  app-network:
    driver: bridge
