services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    branch: main
    autoDeploy: true
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "file:/app/prisma/dev.db"
