services:
  - type: web
    name: backend
    env: node
    branch: main
    rootDir: backend  
    autoDeploy: true
    plan: free
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
    startCommand: node dist/index.js
    envVars:
      - key: DATABASE_URL
        value: "file:/opt/render/project/src/backend/prisma/dev.db"
