services:
  - type: web
    name: backend
    env: node
    branch: main
    autoDeploy: true
    plan: free
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
    startCommand: node dist/index.js
    envVars:
      - key: DATABASE_URL
        value: "file:./prisma/dev.db"
